config/routes.rb
Rails.application.routes.draw do
  root 'todos#home'
  resources :todos #automatically includes all basic CRUD routes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all #returns all todos in the database
  end

  def show
    @todo = Todo.find(params[:id]) #finds a todo by the id passed in
  end

  def new
    @todo = Todo.new #creates a new page in memory (not in database)
  end

  def create
    @todo = Todo.new(todos_params)

    if @todo.save
      redirect_to todos_path
    else
      render :new
    end
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])

    if @todo.update(todos_params)
      redirect_to todo_path(@todo)
    else
      render :edit
    end
  end

  def destroy
    Todo.find(params[:id]).destroy
    redirect_to todos_path
  end

  private
    def todos_params
      params.require(:todo).permit(:title, :body, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', todos_path %>
<%= link_to 'Welcome', root_path %>
<%= link_to 'About', todos_path %>
<%= link_to 'Todo List', todos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/todos/edit.html.erb
<h1>Edit List</h1>
<%= form_for @todo do |f| %>
  <%= f.label 'Task' %>
  <%= f.text_field :title %>

  <%= f.label 'Description' %>
  <%= f.text_field :body %>

  <p>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  </p>
  
  <%= f.submit %>
<% end %>

app/views/todos/home.html.erb
<h1>Welcome!</h1>
<p>Do you keep "forgetting" the things you have to do? Write
  them down and check them off as you finish them with this 
  todo list! Now you'll never forget again.</p>

<p><%= link_to "Let's Get Started!", todos_path %></p>

app/views/todos/index.html.erb
<h1>- Todo List -</h1>
<p><%= link_to 'Create a New Task', new_todo_path %></p>
<% @todos.each do |todo| %>
  <h2><%= todo.title %></h2>
  <%= link_to 'Show task', todo_path(todo) %>
  <%= link_to 'Edit task', edit_todo_path(todo) %>
  <%= link_to 'Delete task', todo, method: :delete %>
<% end %>

app/views/todos/new.html.erb
<h1>New Todo List</h1>
<%= form_for @todo do |f| %> <%# rails helper that creates a form %>
  <%= f.label :title %> 
  <%= f.text_field :title %>

  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.label :completed %>
  <%= f.check_box :completed %>

  <%= f.submit %>
<% end %>

app/views/todos/show.html.erb
<h1>TASK: <%= @todo.title %></h1>
<h4>DESCRIPTION: <%= @todo.body %></h4>
<%= form_for @todo do |f|%>
  <%= f.label :completed %>
  <%= f.check_box :completed %>

  <%= f.submit %>
<% end %>
<br />
<%= link_to 'Back', todos_path %>